### ISSUE TITLE
Deployment and connection to a remote server

### ISSUE THREAD

**Issue by JulienSambre** [nicho92/MtgDesktopCompanion#175]
Hi!

I discovered MtgDesktopCompanion and it seems to be very complete in order to manage decks & collections.

One of my needs would be to separate client side and server side in order to store my library/decks server side and to access it with the client side over the Internet.

It seems to be possible when I look the features ("Multi Database : MySQL, Postgres, Hsql, MongoDB", "Standalone servers"), but I have not found any configuration or deployment documentation about it.

Does anybody tried this before?

Thanks :).

**Comment by nicho92** [comment]
Hi,

Sure it's possible.

Just setup a database with network access ( ex : opening 3307 for mysql),
you can also try MongoDB which offers free hosting
then in MTGCompanion, you just have to configure network information in
Configuration/Pluggins/Database

[image: image.png]

**Comment by JulienSambre** [comment]
Thanks for the quick answer :).

If I understand, there is no webserver backend for the Java GUI, like there is for Web Server UI?

![image](https://user-images.githubusercontent.com/14327288/126942939-4200013f-7890-4fb3-a540-0f94e99b106f.png)

If not, a synchronized database (with nextcloud client for example) would work perfectly among my multiple computers: exposing a database on the Internet is a bit unsecure :).


For the Web Server UI, do I have to open both 80 and 8080 port on the Internet or only the 80 is enough?

**Comment by nicho92** [comment]
Hi ,

Java GUI (rich client) is working only with a database connection (external
or local) . That's why I'm using MongoCLoud for my production db :)
The JSonServer is for Web UI Server and ShopServer (or other external
service).

The webUI listens  80, and JsonServer 8080 (by default). You can change it
in the properties of servers.
Both should be opened for the internet.

By the way, if you want to store your website page to another web provider,
you can extract the pages through the config panel :

[image: image.png]

Just put good IP in the WebServer REST_BACKEND_URI before ;)

**Comment by JulienSambre** [comment]
Perfectly clear, thanks for all the quick answers and tips ;)!
